/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import model.ClientAccount_DAO;
import model.Client_DAO;

/**
 *
 * @author Gabriel
 */
public class Index_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Index_GUI
     */
    public Index_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        clientName_txt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        confirm_btn = new javax.swing.JButton();
        createAccount_btn = new javax.swing.JButton();
        exit_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        jLabel1.setText("Digital Bank");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(170, 20, 70, 16);

        clientName_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientName_txtActionPerformed(evt);
            }
        });
        jPanel1.add(clientName_txt);
        clientName_txt.setBounds(190, 120, 130, 24);

        jLabel2.setText("Type your Account name: ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 120, 170, 30);

        confirm_btn.setText("Confirm");
        confirm_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirm_btnActionPerformed(evt);
            }
        });
        jPanel1.add(confirm_btn);
        confirm_btn.setBounds(160, 170, 90, 40);

        createAccount_btn.setText("Create an account");
        createAccount_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAccount_btnActionPerformed(evt);
            }
        });
        jPanel1.add(createAccount_btn);
        createAccount_btn.setBounds(130, 230, 160, 32);

        exit_btn.setText("X");
        exit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_btnActionPerformed(evt);
            }
        });
        jPanel1.add(exit_btn);
        exit_btn.setBounds(340, 0, 60, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(400, 300));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void clientName_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientName_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientName_txtActionPerformed

    private void confirm_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirm_btnActionPerformed
        String clientName = clientName_txt.getText().trim();
        if(clientName.equals("")) { JOptionPane.showMessageDialog(null, "Field can't be null!"); }
        else if(ClientAccount_DAO.accountCheck(clientName)) {
            Client_DAO.actualClient = ClientAccount_DAO.allClients.get(clientName);
            dispose();
            new AccountPage_GUI().setVisible(true);
        }
        else { JOptionPane.showMessageDialog(null, "Account not found"); }
        
        
        
    }//GEN-LAST:event_confirm_btnActionPerformed

    private void createAccount_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAccount_btnActionPerformed
        String clientName = clientName_txt.getText().trim();
        if(clientName.equals("")) { JOptionPane.showMessageDialog(null, "Field can't be null!"); }
        else if(!ClientAccount_DAO.accountCheck(clientName)) {
            new ClientAccount_DAO(clientName);
        }
        else { JOptionPane.showMessageDialog(null, "Account already exists"); }
    }//GEN-LAST:event_createAccount_btnActionPerformed

    private void exit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_btnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exit_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Index_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Index_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Index_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Index_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Index_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField clientName_txt;
    private javax.swing.JButton confirm_btn;
    private javax.swing.JButton createAccount_btn;
    private javax.swing.JButton exit_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
